import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Header from "./components/Global/Header";
import Footer from "./components/Global/Footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400","500","600","700","800"], // Include different weights as needed
  variable: "--font-roboto", // Set a CSS variable
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
